version: "3.12"

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 195.168.1.0/24

services:
  postgres:
    image: postgres
    container_name: docker_db
    networks:
      custom_network:
        ipv4_address: 195.168.1.123
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: akanksha
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

  python_app:
    build: .
    # image: my-python-app:latest
    container_name: python_app_container
    networks:
      custom_network:
        ipv4_address: 195.168.1.125
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres:
    driver: local
